controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    # Add effort controllers for the joints we defined in the URDF
    left_shoulder_joint_effort_controller:
      type: effort_controllers/JointEffortController
    left_elbow_joint_effort_controller:
      type: effort_controllers/JointEffortController
    right_shoulder_joint_effort_controller:
      type: effort_controllers/JointEffortController
    right_elbow_joint_effort_controller:
      type: effort_controllers/JointEffortController
    left_hip_joint_effort_controller:
      type: effort_controllers/JointEffortController
    left_knee_joint_effort_controller:
      type: effort_controllers/JointEffortController
    right_hip_joint_effort_controller:
      type: effort_controllers/JointEffortController
    right_knee_joint_effort_controller:
      type: effort_controllers/JointEffortController

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 50

left_shoulder_joint_effort_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
    interface_name: effort

left_elbow_joint_effort_controller:
  ros__parameters:
    joints:
      - left_elbow_joint
    interface_name: effort

right_shoulder_joint_effort_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
    interface_name: effort

right_elbow_joint_effort_controller:
  ros__parameters:
    joints:
      - right_elbow_joint
    interface_name: effort

left_hip_joint_effort_controller:
  ros__parameters:
    joints:
      - left_hip_joint
    interface_name: effort

left_knee_joint_effort_controller:
  ros__parameters:
    joints:
      - left_knee_joint
    interface_name: effort

right_hip_joint_effort_controller:
  ros__parameters:
    joints:
      - right_hip_joint
    interface_name: effort

right_knee_joint_effort_controller:
  ros__parameters:
    joints:
      - right_knee_joint
    interface_name: effort
